version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@procore/core-react"
    versions:
    - 10.0.0
    - 10.0.1
    - 10.4.0
    - 9.8.0
  - dependency-name: react-scripts
    versions:
    - 4.0.3
  - dependency-name: whatwg-fetch
    versions:
    - 3.6.1
